import type { Metadata } from "next";
import Header from "@/components/Header/page";
import Footer from "@/components/Footer/page";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
